%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Enru\Documents\Postdoc UZH\Bingjie_Data\Pb_thresh_values.ods
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 24-Feb-2022 10:48:29

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:B49";

% Specify column names and types
opts.VariableNames = ["Pb", "ThresholdValue"];
opts.VariableTypes = ["double", "double"];

% Import the data
Pbthreshvalues = readtable("C:\Users\Enru\Documents\Postdoc UZH\Bingjie_Data\Pb_thresh_values.ods", opts, "UseExcel", true);

%% Convert to output type
Pbthreshvalues = table2array(Pbthreshvalues);

%% Clear temporary variables
clear opts

%% Calculating the percentile place for each participant's threshold values

n = 1;     %counter for threshold values table

for subjectIdx = [28:54 56:76]
    %[r, c] = find(~isnan(pb(subjectIdx).smoothedICvEOG));                  %Run this line if timePts variable is not available. Find the last non-nan value for each participant
    nless = sum(pb(subjectIdx).smoothedICvEOG < Pbthreshvalues(n, 2), 'omitnan');
    nequal = sum(pb(subjectIdx).smoothedICvEOG == Pbthreshvalues(n, 2), 'omitnan');
    centile = 100 * (nless + 0.5*nequal) / timePts(n, 1);
    %centile = 100 * (nless + 0.5*nequal) / max(c);
    Pbthreshvalues(n, 3) = centile;
    n = n + 1;
end

save('Pb_thresh_values_w_prctiles.mat', 'Pbthreshvalues');